### ISSUE TITLE
列幅の自動調整がうまく効かないときがある？

### ISSUE THREAD

**Issue by kbtaniguchi** [luchta-io/forma4j#195]
#157 で対応した内容が環境によって適切に機能しないことがありそう

**Comment by kbtaniguchi** [comment]
日本語フォントの場合に幅の自動調整がうまくいかないケースがある模様、環境というよりデータ起因？
https://nekotheshadow.github.io/qiita-backup/blog/2dcf0c8275317135733b/

**Comment by yamazakihitoshi** [comment]
日本語フォントを指定すると自動調整がうまくいくという記事を見かけたので試してみた。
https://qiita.com/neko_the_shadow/items/2dcf0c8275317135733b

```java
CellStyle cellStyle = workbook.createCellStyle();
Font font = workbook.createFont();
font.setFontName("Calibri");
```

`Calibri` 以外にもいくつかのフォントで試したが自動調整が全ての列に対してうまくいくケースはなかった。

**Comment by yamazakihitoshi** [comment]
別途対応済みのためクローズ。
